import { Inter } from 'next/font/google';

import './globals.css';
import { SessionProvider } from 'next-auth/react';
import { auth } from '@/auth';
import { Navbar } from './(protected)/_components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          {session?.user?.email ? <Navbar /> : <div>Not logged in navbar</div>}

          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
